language: csharp
solution: Ravitej.Automation.All.sln
mono:
  - latest
install:
  - nuget restore Ravitej.Automation.All.sln
  - nuget install NUnit.Runners -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Ravitej.Automation.All.sln
  - mono ./testrunner/NUnit.Runners.*/tools/nunit-console.exe ./CoreFramework/Tests/Ravitej.Automation.Common.Tests/bin/Release/Ravitej.Automation.Common.Tests.dll
